"""
List of penetration targets
"""

khamenei2 = "www.khamenei.ir"
astan_ghods = "www.aqr.ir"
panzdah_khordad = "www.15khordad42.ir"
bonyad_shahid = "www.isaar.ir"
bonyad_mostazafan = "www.irmf.ir"
bonyad_maskan = "www.bonyadmaskan.com"
oghaf = "www.oghaf.ir"
tablighat_eslami = "www.ido.ir"
haj = "www.haj.ir"
seda_sima = "www.irib.ir"
ertebatat_eslami = "www.icro.ir"
shora_negahban = "www.shora-gc.ir"
sepah = "www.sepahnews.com"
emam_jome_ha = "www.imamatjome.com"
shora_ali_enghelab_farhangi = "www.sccr.ir"
shora_ali_ghoran = "www.shora.ir"
shora_hamahangi_tablighat_eslami = "www.ccoip.ir"
ghove_ghazaie = "www.dadiran.ir"
komite_emdad = "www.emdad.ir"
etelaat = "www.ettelaat.com"
keyhan = "www.kayhan.ir"
majma_tashkhis_maslahat = "www.maslahat.ir"
markaz_nashr_quran = "www.moshaf.org"
markaz_meli_faza_majazi = "www.majazi.ir"
nahad_rahbar_in_universities = "www.nahad.ir"
defa_moghadas = "www.defapress.ir"
khomeini = "www.imam-khomeini.ir"
khorasani = "www.wahidkhorasani.com"
safi_golpaygani = "www.saafi.com"
makarem_shirazi = "www.makarem.ir"
nori_hamedani = "www.noorihamedani.com"
javadi_amoli = "www.esra.ir"
jafar_sobhani = "www.tohid.ir"
hashemi_shahrudi = "www.hashemishahroudi.org"
khamenei1 = "www.leader.ir"
president = "www.president.ir"
majles_shora_eslami = "www.parliran.ir"
majles_khobregan = "www.majlesekhobregan.ir"
government = "www.dolat.ir"
isna = "www.isna.ir"
irna = "www.irna.ir"
